### ISSUE TITLE
Linux Raspberry Pi 3 (Ubuntu)

### ISSUE THREAD

**Issue by samelie** [macacajs/nodecv-server#1]
Hi, thanks for your efforts.

I have opencv 2.4.13 installed.
First I had to run `npm config set unsafe-perm true` then install `node-gyp`

When I run `make server` I get this error.

```
/home/pi/github/nodecv-server/node_modules/bindings/bindings.js:83
        throw e
        ^
Error: libopencv_nonfree.so.2.4: cannot open shared object file: No such file or directory
```

Are you generating this file? Any ideas what to do?

**Comment by xudafeng** [comment]
@samelie

Missing dynamic-link library file？

try this: 
```
$ ldconfig
```

https://github.com/xudafeng/nodecv/blob/master/Dockerfile

**Comment by samelie** [comment]
@xudafeng Excellent! Your demo works. Nice! Learning more about what's going on under the hood.
This opencv RP3 install [guide](http://ivanha.github.io/blog/2015/05/16/install-opencv-on-raspberry-pi/) worked just fine.
You should also build [ffmpeg](https://www.jeffreythompson.org/blog/2014/11/13/installing-ffmpeg-for-raspberry-pi/) from source before.
