### ISSUE TITLE
安装到node-gyp 总是失败

### ISSUE THREAD

**Issue by lylh** [macacajs/nodecv-server#3]
npm i
`
> nodecv@1.0.5 install /Users/lylh/Documents/workspace/iPhoneProject/pythonProject/nodecv-server/node_modules/nodecv
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
/Users/lylh/Documents/workspace/iPhoneProject/pythonProject/nodecv-server/node_modules/nodecv/scripts/find-opencv.js:11
    throw new Error('ERROR: failed to run: pkg-config');
    ^

Error: ERROR: failed to run: pkg-config
    at exec (/Users/lylh/Documents/workspace/iPhoneProject/pythonProject/nodecv-server/node_modules/nodecv/scripts/find-opencv.js:11:11)
    at ChildProcess.exithandler (child_process.js:213:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
gyp: Call to 'node scripts/find-opencv.js --cflags' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/lylh/Documents/workspace/iPhoneProject/pythonProject/nodecv-server/node_modules/nodecv
gyp ERR! node -v v6.9.4
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! nodecv@1.0.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodecv@1.0.5 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nodecv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nodecv
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nodecv
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/lylh/Documents/workspace/iPhoneProject/pythonProject/nodecv-server/npm-debug.log`

**Comment by xudafeng** [comment]
server/node_modules/nodecv/scripts/find-opencv.js:11
throw new Error('ERROR: failed to run: pkg-config');
^

Error: ERROR: failed to run: pkg-config 


查这个问题
