### ISSUE TITLE
Hi ，how to build the server?use npm or docker?

### ISSUE THREAD

**Issue by yangxinQA** [macacajs/nodecv-server#4]
i  read in test home that （build with nam）：
$ git clone git@github.com:macacajs/nodecv-server.git --depth=1
$ cd nodecv-server
$ npm i
$ make server
and in the maraca :(build with docker )
$ git clone git@github.com:macacajs/nodecv-server.git --depth=1
$ cd nodecv-server
$ docker build . -t="node-server"

```
_B000000081679:nodecv-server yangx$ docker build -t="node-server" .
Sending build context to Docker daemon 590.8 kB
Step 0 : FROM xudafeng/nodecv
 ---> 2e42dae8cd9d
Step 1 : COPY . /nodecv-server
 ---> Using cache
 ---> e84db874160d
Step 2 : ENTRYPOINT /nodecv-server/entrypoint.sh
 ---> Using cache
 ---> 58909b7771f0
Successfully built 58909b7771f0_
```
i build with docker and it show build successfully ,but i can not open the link:
http://localhost:9900/opencv/demo

how to solve the problem?

**Comment by xudafeng** [comment]
https://github.com/macacajs/nodecv-server/blob/master/Makefile#L24

**Comment by yangxinQA** [comment]
@xudafeng  hi ，亲，我没看懂额，能解释的详细点么？我用中文描述一下我的问题哦。
我在 testerhome 上看到用npm 部署那个 server
$ cd nodecv-server
$ npm i
$ make server
在 macaca 官网上看到用 docker 部署。
$ git clone git@github.com:macacajs/nodecv-server.git --depth=1
$ cd nodecv-server
$ docker build . -t="node-server"
我试着用 docker  #部署了，然后提示部署成功，但是我打不开链接demo页？所以到底用啥部署？
求救
http://localhost:9900/opencv/demo

_B000000081679:nodecv-server yangx$ docker build -t="node-server" .
Sending build context to Docker daemon 590.8 kB
Step 0 : FROM xudafeng/nodecv
 ---> 2e42dae8cd9d
Step 1 : COPY . /nodecv-server
 ---> Using cache
 ---> e84db874160d
Step 2 : ENTRYPOINT /nodecv-server/entrypoint.sh
 ---> Using cache
 ---> 58909b7771f0
Successfully built 58909b7771f0_

**Comment by yangxinQA** [comment]
解决了，可能是网速问题。。。我换成淘宝的 npm 然后 ok 了 cnpm i 这个命令。不过 makeServer 报错
@nodecv/compiled/8.1.0/darwin/x64/nodecv.node
    at bindings (/Users/yx/Documents/macaca_opencv/nodecv-server/node_modules/_bindings@1.2.1@bindings/bindings.js:88:9)
    at Object.<anonymous> (/Users/yx/Documents/macaca_opencv/nodecv-server/node_modules/_nodecv@1.0.5@nodecv/lib/nodecv.js:5:31)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/yx/Documents/macaca_opencv/nodecv-server/node_modules/_nodecv@1.0.5@nodecv/index.js:3:18)

**Comment by xudafeng** [comment]
@yangxinQA 你是windows用户啊?make用不了，直接docker执行吧。

**Comment by yangxinQA** [comment]
@xudafeng 亲，我是 mac 用户。docker 我试了。提示 build successfully（就像下面的提示）。然后打不开网页呢 http://localhost:9900/opencv/demo 这个链接打不开
B000000081679:nodecv-server yangx$ docker build -t="node-server" .
Sending build context to Docker daemon 590.8 kB
Step 0 : FROM xudafeng/nodecv
---> 2e42dae8cd9d
Step 1 : COPY . /nodecv-server
---> Using cache
---> e84db874160d
Step 2 : ENTRYPOINT /nodecv-server/entrypoint.sh
---> Using cache
---> 58909b7771f0
Successfully built 58909b7771f0

**Comment by xudafeng** [comment]
mac用户可以直接启动的 https://github.com/macacajs/nodecv-server/blob/master/Makefile#L24。可以不用docker

**Comment by yangxinQA** [comment]
按照你的方法
CD 到 nodecv-server目录后，
cnpm i
 make 
下面是日志，感觉没报错，就是打不开网页。很奇怪呀。^-^?
macaca yangxin09$ cd /Users/yx/Documents/macaca_opencv/nodecv-server 
B000000081679:nodecv-server yangxin09$ cnpm i
✔ Installed 20 packages
✔ Linked 0 latest versions
✔ Run 0 scripts
✔ All packages installed (used 31ms, speed 0B/s, json 0(0B), tarball 0B)
B000000081679:nodecv-server yangxin09$ make


  test
    ✓ should be ok


  1 passing (15ms)

=============================================================================
Writing coverage object [/Users/yx/Documents/macaca_opencv/nodecv-server/coverage/coverage.json]
Writing coverage reports at [/Users/yx/Documents/macaca_opencv/nodecv-server/coverage]
=============================================================================

=============================== Coverage summary ===============================
Statements   : 52% ( 13/25 )
Branches     : 100% ( 0/0 )
Functions    : 100% ( 0/0 )
Lines        : 52% ( 13/25 )
================================================================================
B000000081679:nodecv-server yangxin09$

**Comment by xudafeng** [comment]
我发你的这行是 make server 不是 make吧

**Comment by yangxinQA** [comment]
make server时报错如下 。这些文件都不存在呢？
Error: Could not locate the bindings file. Tried:
 → /Users/baidu/Documents/macaca_opencv/node_modules/_nodecv@1.0.5@nodecv/build/nodecv.node
 → /Users/baidu/Documents/macaca_opencv/node_modules/_nodecv@1.0.5@nodecv/build/Debug/nodecv.node
 → /Users/baidu/Documents/macaca_opencv/node_modules/_nodecv@1.0.5@nodecv/build/Release/nodecv.node
 → /Users/baidu/Documents/macaca_opencv/node_modules/_nodecv@1.0.5@nodecv/out/Debug/nodecv.node
 → /Users/baidu/Documents/macaca_opencv/node_modules/_nodecv@1.0.5@nodecv/Debug/nodecv.node
 → /Users/baidu/Documents/macaca_opencv/node_modules/_nodecv@1.0.5@nodecv/out/Release/nodecv.node
 → /Users/baidu/Documents/macaca_opencv/node_modules/_nodecv@1.0.5@nodecv/Release/nodecv.node
 → /Users/baidu/Documents/macaca_opencv/node_modules/_nodecv@1.0.5@nodecv/build/default/nodecv.node
 → /Users/baidu/Documents/macaca_opencv/node_modules/_nodecv@1.0.5@nodecv/compiled/8.1.0/darwin/x64/nodecv.node
    at bindings (/Users/baidu/Documents/macaca_opencv/node_modules/_bindings@1.2.1@bindings/bindings.js:88:9)
    at Object.<anonymous> (/Users/baidu/Documents/macaca_opencv/node_modules/_nodecv@1.0.5@nodecv/lib/nodecv.js:5:31)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/baidu/Documents/macaca_opencv/node_modules/_nodecv@1.0.5@nodecv/index.js:3:18)

**Comment by xudafeng** [comment]
应该是没安装成功，按照安装过程中的报错提示重装
